# Generated by Django 3.1.5 on 2021-02-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210204_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passengerNum',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)]),
        ),
    ]
