# Generated by Django 3.1.5 on 2021-02-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210204_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='area',
            field=models.CharField(choices=[('North', 'N'), ('South', 'S'), ('East', 'E'), ('West', 'W'), ('Central Area', 'C')], default='None', max_length=999),
        ),
    ]
