# Generated by Django 3.1.5 on 2021-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_ride_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_id',
            new_name='driverId',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='owner_id',
            new_name='ownerId',
        ),
        migrations.AlterField(
            model_name='ride',
            name='area',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West'), ('C', 'Central Area')], default='None', max_length=999),
        ),
    ]
