# Generated by Django 3.1.5 on 2021-02-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210204_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='shareable',
            field=models.BooleanField(default=False),
        ),
    ]
